# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Storage'
target 'UCSCForum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UCSCForum

  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  
  target 'UCSCForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UCSCForumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
